title: Kubernetes Home Laboratory
email: diegopc99@gmail.com
description: >-
  Basic Instructions for Creating Your Own Kubernetes-Based Home Laboratory
baseurl: "/home-lab/"
url: "https://diegopc99.github.io" 
github_username:  diegopc99

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed